language: cpp
compiler: clang
sudo: required
dist: trusty

branches:
  except:
    - gh-pages

env:
  global:
    - GH_REPO_NAME: otus_cpp_lesson_08
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/chernikoff/otus_cpp_lesson_08.git

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libgtest-dev doxygen graphviz
  - mkdir build-gtest
  - cd build-gtest
  - cmake /usr/src/gtest
  - cmake --build .
  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"
    
script:
  - cmake .
  - cmake --build .
  - ctest -V
  - cmake --build . --target package

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x scripts/generateDocumentationAndDeploy.sh
  - scripts/generateDocumentationAndDeploy.sh

deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uchernikoff:$BINTRAY_API_KEY "https://api.bintray.com/content/chernikoff/otus/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1;"
